### ISSUE TITLE
Faction Chat not getting detected?

### ISSUE THREAD

**Issue by EaterSteam** [np6hd/factionsBot#1]
Sorry to bother again :'D, but now its not detecting the faction chat and hence the .token is also not working (my guess)
If you have discord, then pls DM me (Eater#2751) and i can directly msg u there instead 

Below is a pic of the server chat channel, it doesnt detect the faction chat
http://prntscr.com/ungvkz

**Comment by np6hd** [comment]
Yea send me your discord I’ll af you once I’m on my computer, can you also
send me the ip so I can check it out?

**Comment by EaterSteam** [comment]
Eater#2751
